import { Declaration } from "../../../model/declaration";

export const initialDeclaration: Declaration = {
  accidentLatLng: { latitude: 0, longitude: 0 },
  datetime: new Date(Date.now()),
  accidentCountryLocation: "Lithuania",
  peopleInjuries: "No",
  damageToCars: true,
  damageToObjects: false,
  witnesses: "",
  firstCar: {
    insurer: {
      familyName: "",
      name: "",
      address: "",
      postalCode: "",
      country: "",
      contacts: "",
    },
    car: {
      carModel: "",
      carCountryPlate: "",
      carCountryRegistration: "",
    },
    insurance: {
      insuranceCompanyName: "",
      insurancePolicyNumber: "",
      insuranceGreenCardNumber: "",
      insuranceValidFrom: new Date(Date.now()),
      insuranceValidTo: new Date(Date.now()),
    },
    insurancePolicyCoverage: false,
    driver: {
      familyName: "",
      name: "",
      address: "",
      postalCode: "",
      country: "",
      contacts: "",
      drivingLicenceNumber: "",
      drivingLicenceCategory: "",
      drivingLicenceExpirationDate: new Date(Date.now()),
    },
    damageImpactLocation: "N",
    damageDescription: "",
    circumstances: {
      standing: false,
      stopping: false,
      openingTheDoor: false,
      braking: false,
      leavingParkingSpace: false,
      leavingPrivatePlot: false,
      leavingRoadside: false,
      enteringParkingSpace: false,
      enteringPrivatePlot: false,
      enteringRoadside: false,
      enteringRoundabout: false,
      drivingRoundabout: false,
      hittingRearWhenDrivingInSameDirection: false,
      drivingInTheSameDirectionButDifferentLane: false,
      changingLanes: false,
      overtaking: false,
      turningRight: false,
      turningLeft: false,
      reversing: false,
      enteringOncomingLane: false,
      hittingAtAnIntersectionFromTheRight: false,
      notGivingWayWhenRedTrafficLight: false,
    },
  },
  secondCar: {
    insurer: {
      familyName: "",
      name: "",
      address: "",
      postalCode: "",
      country: "",
      contacts: "",
    },
    car: {
      carModel: "",
      carCountryPlate: "",
      carCountryRegistration: "",
    },
    insurance: {
      insuranceCompanyName: "",
      insurancePolicyNumber: "",
      insuranceGreenCardNumber: "",
      insuranceValidFrom: new Date(Date.now()),
      insuranceValidTo: new Date(Date.now()),
    },
    insurancePolicyCoverage: false,
    driver: {
      familyName: "",
      name: "",
      address: "",
      postalCode: "",
      country: "",
      contacts: "",
      drivingLicenceNumber: "",
      drivingLicenceCategory: "",
      drivingLicenceExpirationDate: new Date(Date.now()),
    },
    damageImpactLocation: "N",
    damageDescription: "",
    circumstances: {
      standing: false,
      stopping: false,
      openingTheDoor: false,
      braking: false,
      leavingParkingSpace: false,
      leavingPrivatePlot: false,
      leavingRoadside: false,
      enteringParkingSpace: false,
      enteringPrivatePlot: false,
      enteringRoadside: false,
      enteringRoundabout: false,
      drivingRoundabout: false,
      hittingRearWhenDrivingInSameDirection: false,
      drivingInTheSameDirectionButDifferentLane: false,
      changingLanes: false,
      overtaking: false,
      turningRight: false,
      turningLeft: false,
      reversing: false,
      enteringOncomingLane: false,
      hittingAtAnIntersectionFromTheRight: false,
      notGivingWayWhenRedTrafficLight: false,
    },
  },
  culprit: {
    fullName: "",
  },
};
