export enum Circumstance {
  standing = "standing",
  stopping = "stopping",
  openingTheDoor = "openingTheDoor",
  braking = "braking",
  leavingParkingSpace = "leavingParkingSpace",
  leavingPrivatePlot = "leavingPrivatePlot",
  leavingRoadside = "leavingRoadside",
  enteringParkingSpace = "enteringParkingSpace",
  enteringPrivatePlot = "enteringPrivatePlot",
  enteringRoadside = "enteringRoadside",
  enteringRoundabout = "enteringRoundabout",
  drivingRoundabout = "drivingRoundabout",
  hittingRearWhenDrivingInSameDirection = "hittingRearWhenDrivingInSameDirection",
  drivingInTheSameDirectionButDifferentLane = "drivingInTheSameDirectionButDifferentLane",
  changingLanes = "changingLanes",
  overtaking = "overtaking",
  turningLeft = "turningLeft",
  turningRight = "turningRight",
  goingStraightAhead = "goingStraightAhead",
  reversing = "reversing",
}
